const imra_aparencia = `Ele tem a pele num tom de cinza chumbo que serve de fundo para um monte de sardas brancas no nariz e nas bochechas, parecendo literalmente poeira estelar. No braço dele, tem até umas linhas finas desenhando constelações direto na pele. O cabelo é preto, meio repicado e bagunçado, e os olhos são quase totalmente escuros. Ele usa um cachecol azul bem chamativo cobrindo o pescoço, com umas pontas super longas que ficam esvoaçando atrás dele, quase se misturando com a magia. No tronco, ele veste uma regata preta justa enfeitada com umas correntes prateadas fininhas cruzando o peito. Para completar, usa calças azuis bem largas e folgadas`;

const imra_pers_texto = `
<p>Imra tem uma personalidade forte e uma determinação quase inabalável. Geralmente sabe exatamente o que quer e dificilmente recua depois de tomar uma decisão. É impulsivo, franco e costuma agir antes mesmo que as dúvidas consigam alcançá-lo. Ainda assim, tem um lado discreto, tentando ao máximo camuflar o que realmente sente. Independentemente da situação, faz questão de sustentar a imagem de alguém forte, mesmo quando está desmoronando por dentro. Ele não busca liderança nem é movido por grandes ambições. Vê-se como um guardião, alguém que está aqui para proteger os outros, seja como um escudo ou como uma arma quando a situação exigir. Sua própria vida raramente ocupa o primeiro lugar em suas prioridades, pois acredita que seu valor está naquilo que pode fazer pelos demais. Imra é orgulhoso, competitivo e, por vezes, arrogante. Odeia ser superado e faz de tudo para provar seu próprio valor. No entanto, por trás dessa atitude desafiadora, há uma pessoa que realmente está disposta a ajudar quem precisa, mesmo que isso tenha um alto custo para ela. Quando o assunto são seus próprios sentimentos, torna-se extremamente fechado. Tem dificuldade em falar sobre si e costuma reagir de maneira hostil ou defensiva quando alguém tenta compreender suas emoções. Para ele, demonstrar vulnerabilidade é o mesmo que abrir uma brecha em sua armadura. Apesar disso, possui uma presença naturalmente extrovertida. Gosta de chamar atenção, provocar reações e interagir com as pessoas, comunicando-se com facilidade e raramente demonstrando timidez. Seu carisma frequentemente esconde conflitos internos que poucos conseguem perceber.</p>
<p>Embora saiba que não é invencível, seu orgulho jamais permite que demonstre fraqueza. Imra enfrentará qualquer desafio de cabeça erguida e lutará até o último instante antes de aceitar uma derrota, pois acredita que desistir de si mesmo seria a única derrota verdadeiramente imperdoável.</p>

`;

const imra_signo_desc = `Imra teria ligação com Áries pois sua personalidade é marcada pela intensidade com que vive. Ele é firme e dificilmente reverte suas escolhas, agindo por impulso ao invés de se deixar levar por incertezas. Geralmente age por impulso e é bastante franco, lidando com as questões de maneira direta e sem se preocupar muito com as repercussões. Seu orgulho é uma das características mais marcantes. Mesmo sabendo que não é invencível, ele sempre tentará permanecer de pé e provar seu valor. É extremamente competitivo, odeia ser derrotado e dificilmente aceita recuar, insistindo em seguir em frente mesmo quando tudo parece dizer o contrário. Apesar da postura firme, Imra não busca liderança nem grandes ambições. Ele se vê como alguém que está aqui para proteger os outros, como um escudo ou uma arma quando necessário. Sua própria vida raramente é sua prioridade, pois acredita que seu verdadeiro valor está em quem consegue manter seguro. Ao mesmo tempo, ele faz de tudo para esconder aquilo que sente. Tem dificuldade em expressar seus sentimentos e, quando alguém tenta se aproximar, acaba reagindo com hostilidade, preferindo lidar com seus problemas sozinho a mostrar qualquer fraqueza. Mesmo assim, Imra é naturalmente extrovertido. Adora um bate-papo, estar no centro das atenções e se envolver com os outros, utilizando seu estilo confiante e provocante como uma forma de disfarçar tudo o que mantém para si. No fim, ele é alguém que vive sempre em movimento, sustentado pelo próprio orgulho e pela vontade de continuar seguindo em frente, não importa o quanto o caminho tente fazê-lo parar.  `;

const imra_visao_desc = `Imra ama profundamente sua irmã. Desde o dia em que ela nasceu, ele passou a enxergá-la como o maior presente que a vida poderia lhe dar, como se o destino tivesse colocado os dois no mesmo dia para que um existisse pelo outro. Desde então, assumiu para si a responsabilidade de protegê-la, sempre agindo como um verdadeiro irmão mais velho. Para Imra, a vida dela sempre estará acima da sua. Ele não hesitaria em se sacrificar caso isso significasse vê-la segura. Muitas das coisas que faz, das escolhas que toma e dos esforços que suporta têm apenas um objetivo, proporcionar a ela uma vida melhor, cheia de conforto e felicidade, mesmo que isso custe a própria paz. Aos seus olhos, sua irmã é como uma delicada taça de vidro. Extremamente frágil, capaz de se partir diante da menor violência do mundo, mas ao mesmo tempo dona de uma beleza impossível de descrever. Justamente por enxergá-la dessa forma, Imra acredita que é seu dever permanecer entre ela e qualquer ameaça, tornando-se o escudo que impedirá o mundo de tirar seu brilho. Mais do que protegê-la, Imra sente que sua própria existência só faz sentido enquanto puder vê-la sorrir. Se um dia precisasse escolher entre a própria vida e a dela, jamais haveria dúvida em seu coração sobre qual delas deveria ser salva.`;
