const nyev_aparencia = `Sua pele é de um tom cinza claro, iluminado por pequenos pontos de luz, focados principalmente em seus ombros. Na região de sua clavícula é possível ver uma estrela negra, símbolo principal de sua raça, os cadentes. Os fios de cabelo são o seu maior destaque, é de um tom de rosa vivido que se destoa das cores desaturadas de seu corpo, tomando forma de um "pixie cut" mal cortado, puxando apenas uma mecha longa e criando duas pontas no topo, lembrando levemente uma aparência de morcego. Já seus olhos, mesmo acompanhando a falta de saturação do resto do corpo puxando para um tom levemente roxo, quase branco, são sempre brilhantes e lacrimejantes, por algum motivo ela sempre tem uma lágrima no canto de seus olhos, mesmo na mais pura felicidade. Por ser uma presença mais introvertida, ela tem uma leve concunda, nada muito aparente, mas já sendo o suficiente para causa-la insegurança, ela tenta se manter vigilante de sua postura. Esse seu aspecto negativo, também a faz ter uma expressão natural mais recuada, quem não a conhece normalmente acha que está sempre pra baixo, mesmo só estando olhando a vista com um rosto calmo.`;

const nyev_pers_texto = `
<p> Nyev é uma garota introspectiva, uma observadora silenciosa do mundo ao seu redor. Ela não costuma ser a primeira a puxar assunto, pois cada palavra parece pesar uma tonelada antes de ser dita, e o medo de tentar a mantém refém de seus próprios pensamentos. Mas por dentro, há sempre a vontade, uma ânsia genuína, de criar novas amizades, de se conectar. Então, mesmo sempre acreditando e repetindo para si que: "amizades de qualidade valem mais que qualquer quantidade", ela, por vezes, sonha em ter a quantidade também, em ser notada, fazer amigos e sentir que também pertence a algo maior que seu próprio silêncio.</p>
<p>   De início, seus traços e maneirismos a fazem parecer alguém triste e rígida, os ombros levemente curvados, o olhar que foge do contato direto, mas na verdade sua personalidade é o contrário! Ela tem um jeito gentil e amigável, que ela realmente se esforça para trazer mais à tona, como quem tenta desabrochar uma flor em solo árido. Por vezes pode ser desastrada também, tropeçando nas próprias palavras, assim, criando a mania de sempre olhar em volta depois de errar algo, só para ter certeza que ninguém a viu. </p>
<p>   Entretanto, ela também tem uma natureza naturalmente pessimista, uma voz interna que sussurra cenários catastróficos, mas mesmo assim ela sempre tenta ao máximo repetir frases positivas para si, com a esperança de fazer suas preocupações e ansiedades desaparecerem.</p>
<p>   Assim, com um pouco de esforço para se aproximar dela, uma pergunta paciente, um sorriso que não cobra resposta, você é capaz de enxergar uma Nyev bem mais relaxada, e com menos vergonha de se expressar. Você percebe que ela pode ser uma ouvinte leal, que inclina a cabeça com atenção genuína e tenta achar as mais diversas soluções para seus problemas, e admira suas conquistas, ainda mais o esforço que você colocou nelas. Para Nyev, o tempo investido em uma amizade é uma moeda rara, e o esforço colocado na amizade sempre será o mais precioso de todos para ela, um tesouro que ela guarda com cuidado, mesmo quando duvida que mereça tê-lo. </p>
`;

const nyev_signo_desc = `Nyev se conecta com o estigma de Câncer por sua sensibilidade emocional, introspecção e forte instinto de cuidado com os laços que considera preciosos. Assim como o signo, ela vive entre o recolhimento para se proteger e a sua vontade genuína de pertencer. Sua natureza sempre oscila entre o medo da rejeição e o desejo de ser acolhida, e é justamente nessa dualidade que sua alma verdadeira se revela.
Ela carrega consigo uma resiliência sutil, mesmo com seu pessimismo e ansiedade, ela se esforça tentar florescer em meio às dificuldades. Essa força silenciosa, junto de sua natureza protetora e ao cuidado com que nutre suas relações, faz dela um reflexo genuíno do estigma, alguém que sente profundamente, protege com devoção e, mesmo na dúvida, continua acreditando no valor do afeto.`;

const nyev_visao_desc = `  Nyev vê Imra como um irmão mais velho, não apenas no sentido biológico ou casual, mas como aquela figura firme e silenciosa que ocupa um lugar especial em sua vida. Para ela, ele é a presença constante que sempre estará ali, de braços abertos, pronto para escutar até as preocupações mais banais, aquelas que ela mesma considera fútil, mas que, ao serem compartilhadas com ele, ganham peso e acolhimento. Ele sempre estava lá para ela, mesmo que seja apenas para assistirem o nascer do sol juntos em silêncio.
   Essa relação, para Nyev, é essencialmente um refúgio, nele, ela vê um espaço seguro, onde ela pode ser exatamente quem é, é ali que ela se permite fazer piadas bobas, cantarolar músicas sem vergonha, rir à toa e deixar a leveza tomar conta. Mais do que isso, ela sente que, se o mundo inteiro começar a se despedaçar ao redor, se o caos ameaçar engolir tudo, ela pode correr até ele e, de repente, tudo para. O tempo parece se esticar, como se a realidade fizesse uma pausa apenas para conceder-lhes alguns minutos a mais juntos.
   Em seus olhos, Imra é alguém para ser admirado, O que mais a fascina nele é a coragem, a maneira como ele encara os desafios sem hesitar. Inspirada por isso, Nyev tenta, em seus próprios momentos de esforço, se moldar a partir dele, tentando fazer o que ele faria. Ao fazer isso, ela também decide dar uma chance ao destino que os uniu, aceitando que, talvez, suas vidas tenham se cruzado por uma razão maior, e que caminhar ao lado dele é, para ela, uma forma de se tornar mais forte.
`;
