const nyev_aparencia = `Sua pele é de um tom cinza claro, iluminado por pequenos pontos de luz, focados principalmente em seus ombros. Na região de sua clavícula é possível ver uma estrela negra, símbolo principal de sua raça, os cadentes. Os fios de cabelo são o seu maior destaque, é de um tom de rosa vivido que se destoa das cores desaturadas de seu corpo, tomando forma de um "pixie cut" mal cortado, puxando apenas uma mecha longa e criando duas pontas no topo, lembrando levemente uma aparência de morcego. Já seus olhos, mesmo acompanhando a falta de saturação do resto do corpo puxando para um tom levemente roxo, quase branco, são sempre brilhantes e lacrimejantes, por algum motivo ela sempre tem uma lágrima no canto de seus olhos, mesmo na mais pura felicidade. Por ser uma presença mais introvertida, ela tem uma leve concunda, nada muito aparente, mas já sendo o suficiente para causa-la insegurança, ela tenta se manter vigilante de sua postura. Esse seu aspecto negativo, também a faz ter uma expressão natural mais recuada, quem não a conhece normalmente acha que está sempre pra baixo, mesmo só estando olhando a vista com um rosto calmo.`;

const nyev_pers_texto = `
<p> Nyev é uma garota introspectiva, uma observadora silenciosa do mundo ao seu redor. Ela não costuma ser a primeira a puxar assunto, pois cada palavra parece pesar uma tonelada antes de ser dita, e o medo de tentar a mantém refém de seus próprios pensamentos. Mas por dentro, há sempre a vontade, uma ânsia genuína, de criar novas amizades, de se conectar. Então, mesmo sempre acreditando e repetindo para si que: "amizades de qualidade valem mais que qualquer quantidade", ela, por vezes, sonha em ter a quantidade também, em ser notada, fazer amigos e sentir que também pertence a algo maior que seu próprio silêncio.</p>
<p>   De início, seus traços e maneirismos a fazem parecer alguém triste e rígida, os ombros levemente curvados, o olhar que foge do contato direto, mas na verdade sua personalidade é o contrário! Ela tem um jeito gentil e amigável, que ela realmente se esforça para trazer mais à tona, como quem tenta desabrochar uma flor em solo árido. Por vezes pode ser desastrada também, tropeçando nas próprias palavras, assim, criando a mania de sempre olhar em volta depois de errar algo, só para ter certeza que ninguém a viu. </p>
<p>   Entretanto, ela também tem uma natureza naturalmente pessimista, uma voz interna que sussurra cenários catastróficos, mas mesmo assim ela sempre tenta ao máximo repetir frases positivas para si, com a esperança de fazer suas preocupações e ansiedades desaparecerem.</p>
<p>   Assim, com um pouco de esforço para se aproximar dela, uma pergunta paciente, um sorriso que não cobra resposta, você é capaz de enxergar uma Nyev bem mais relaxada, e com menos vergonha de se expressar. Você percebe que ela pode ser uma ouvinte leal, que inclina a cabeça com atenção genuína e tenta achar as mais diversas soluções para seus problemas, e admira suas conquistas, ainda mais o esforço que você colocou nelas. Para Nyev, o tempo investido em uma amizade é uma moeda rara, e o esforço colocado na amizade sempre será o mais precioso de todos para ela, um tesouro que ela guarda com cuidado, mesmo quando duvida que mereça tê-lo. </p>
`;

const nyev_signo_desc = ``;

const nyev_visao_desc = `TESTE TESTE`;
