const nyev_cap1_texto = `
<div class="lore-subchapter">
    <p>Os cosmos, imperfeitos e perfeitos, tudo ao mesmo tempo, se uniam para criar galáxias, planetas, constelações e os astros mais brilhantes possíveis. No meio desse mar de sistemas, dois em específico pareciam estar quase que predestinados a se encontrarem. Na visão humana, afirmar que ambos sempre estiveram mais próximos do que imaginavam, seria incompreensível, eles estavam a milhões de anos-luz um do outro, mas se estrelas tivessem consciência, elas os descreveriam como moradores de uma mesma rua, só esperando para se esbarrarem.</p>
    <p> Assim, as duas estrelas, cansadas de brilhar sozinhas no silêncio do firmamento, como duas moradoras solitárias do vasto universo, começaram a escorregar pelo véu da noite numa curva suave de luz. Suas trajetórias não tinham intenção de se cruzar, mas o destino via aquela oportunidade de outra maneira. Enquanto caía, a estrela segunda foi surpreendida pela presença repentina da estrela segunda, que parecia ter se desviado somente para vê-lá, sem nem terem consciência do fato, dois opostos se completavam. A noite era estrelada e calma, sem nuvens no céu, sem pessoas em volta, apenas dois seres caídos do espaço em uma vasta floresta de pinheiros, eles dormiam suavemente, com os olhos fechados, como se o próprio céu ainda sonhasse dentro deles.</p>
    <p>  Após a fumaça da queda se perder no vento, um par de olhos permanecia fechado como se nada tivesse ocorrido, uma garota de pele cinza clara e de cabelo curto mas rosa vibrante, seus ombros se iluminavam com pequenas estrelas e formavam uma galáxia em volta da região de sua clavícula, onde uma outra estrela, mas desta vez grande e preta como um buraco-negro, tomava conta da região. Mesmo adormecida, seu subconsciente entendia que aquele sono não era solitário. O motivo disso ainda era uma resposta de um futuro distante, já que, nem ela mesma sonhava em se entender ou se quer existir em um plano terreal, ela apenas dormia, sem hora para acordar.</p>
    <p> Aquele sono fundo era quase hipnotizante, fazia você também querer se deitar e alcançar as estrelas mais fofas para dormir, um estado de paz que parecia interrompível, não importa o que você fizesse. Seu sono parecia não ter fim, estações passavam, flores morriam e renasciam, laços se criavam, até mesmo chegavam perto de se rasgar por completo, mas a menina permanecia sonolenta. Ao momento em que seu sono se estendia, qualquer forma de pensamento era imprescindível, não só por ela, mas pela presença que a guardava em meio a este sono. </p>
</div>
`;

const nyev_cap2_texto = `
<p></p>
`;
